<a href="https://colab.research.google.com/github/cherukurikeerthi/FWD/blob/master/python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
my_list = [1,2,3,4,5]
arr_id = np.array(my_list)
print("1-D Array:",arr_id)


1-D Array: [1 2 3 4 5]


In [3]:
list_2d = [[1,2,3],[4,5,6]]
arr_2d = np.array(list_2d)
print("\n2-D Array:")
print(arr_2d)


2-D Array:
[[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np
zero_arr = np.zeros(5)
print("Zero:", zero_arr)
ones_arr = np.ones((2,3))
print("\nones (2x3):")
print(ones_arr)
range_arr = np.arange(10)
print("\nArange (0-9):",range_arr)
lin_arr = np.linspace(0, 1, 5)
print("\nLinspace:",lin_arr)


Zero: [0. 0. 0. 0. 0.]

ones (2x3):
[[1. 1. 1.]
 [1. 1. 1.]]

Arange (0-9): [0 1 2 3 4 5 6 7 8 9]

Linspace: [0.   0.25 0.5  0.75 1.  ]


In [7]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print("array:")
print(arr)
print("\nShape:",arr.shape)
print("Size:",arr.size)
print("Data Type(dtype):",arr.dtype)
print("Number of Dimensions (ndim):",arr.ndim)


array:
[[1 2 3]
 [4 5 6]]

Shape: (2, 3)
Size: 6
Data Type(dtype): int64
Number of Dimensions (ndim): 2


In [9]:
import numpy as np
arr = np.array([1,2,3,4,5])
print("Array:",arr)
print("Elemnt at index 2:",arr[2])
print("Elemnts from index 1 to 3:",arr[1:4])
arr[0]=99
print("\nArray Modification:",arr)

Array: [1 2 3 4 5]
Elemnt at index 2: 3
Elemnts from index 1 to 3: [2 3 4]

Array Modification: [99  2  3  4  5]


In [11]:
import numpy as np
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Elemnet at row 1, column 2:",arr_2d[1,2])
print("First row:",arr_2d[0, :])
print("Second column:",arr_2d[:, 1])

Elemnet at row 1, column 2: 6
First row: [1 2 3]
Second column: [2 5 8]


In [12]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)
print(a+b)
print(b-a)
print(a*b)
print(b/a)
print(a^2)


[1 2 3]
[4 5 6]
[5 7 9]
[3 3 3]
[ 4 10 18]
[4.  2.5 2. ]
[3 0 1]
